services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: 1
